[package]
name = "aw-cosh-hook"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
aw-contracts = { path = "../aw-contracts" }
aw-core = { path = "../aw-core" }
aw-ledger = { path = "../aw-ledger" }
aw-provider-host = { path = "../aw-provider-host" }
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
